# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: slsretoaws
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: node-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  apiGateway:
    restApiId: w0yvm6l4h0
    restApiRootResourceId: ufbtjs0kqd

package:
  individually: true  # Importante: desactivar empaquetado global
  excludeDevDependencies: true  # No incluir devDependencies
  patterns:
        - '!serverless.yml'
        - '!README.md'

functions:
  getUser:
    handler: handlerGet.getUser
    events:
      - http:
          path: /node/find/{id}
          method: GET
    package:
      patterns:
        - 'handlerGet.js'   # Incluir
        - '!handlerPost.js' # Excluir
  postUser:
    handler: handlerPost.createUser
    events:
      - http:
          path: /node/create
          method: POST
    package:
      patterns:
        - 'handlerPost.js'
        - '!handlerGet.js'



